inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  SuggestExtensions: false
  Exclude:
    - ".ruby-lsp/**/*"

Metrics/ParameterLists:
  Enabled: false
