inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  SuggestExtensions: false
  Exclude:
    - ".ruby-lsp/**/*"
    - "db/schema.rb"

Metrics/ParameterLists:
  Enabled: false
