name: swarm-ui

type: ruby

up:
  - ruby
  - bundler
  - gcloud
  - packages:
    - uv
    - tmux
    - ttyd
    - gh
    - redis
    - pkg-config

  - node: 20.10.0
  - custom:
      name: "Install Claude Code globally"
      met?: "npm list -g @anthropic-ai/claude-code"
      meet: "npm install -g @anthropic-ai/claude-code"
  - custom:
      name: "Install gh webhooks extension"
      met?: "gh extension list | grep -q 'cli/gh-webhook'"
      meet: "gh extension install cli/gh-webhook"
  - custom:
      name: "Setup Rails credentials"
      met?: "test -f config/master.key && test -f config/credentials.yml.enc"
      meet: "bin/setup --skip-database --skip-server"
  - database:
      bootstrap: bin/bundle exec rails db:schema:load
      migrate: bin/bundle exec rails db:migrate db:test:prepare
      vendor: sqlite3
      database: storage/development.sqlite3
  - custom:
      name: "GitHub CLI authentication"
      met?: "gh auth status >/dev/null 2>&1"
      meet: "gh auth login"
commands:
  server:
    aliases: ["s"]
    desc: 'start the server'
    run: PORT=4269 TTYD_PORT=4268 bin/start

open:
  app: http://localhost:4269
